name: $(Build.DefinitionName)_$(Date:yyyyMMdd)$(Rev:_r)

# will disable CI builds
trigger: 
  batch: true
  branches:
    include:
    - master
  paths:
    include: 
      - Question_1/Solution_2/pipeline.yaml
    exclude:
      - /*
# will disable PR builds
pr: none 

variables:
  ACR_CONNECTION_NAME: 'ACR_CHALLENGE'
  ACR_URL: 'azcontregxpto.azurecr.io'
  BRANCH_NAME: 'branch-2.3'
  IMAGE_NAME: 'spark'

stages:
- stage: CreateContainerImage
  displayName: Create Container Image
  jobs:
  - job: DockerBuild
    pool: Hosted Ubuntu 1604
    displayName: Create Docker container Image
    workspace:
      clean: all
    steps:
    - task: DockerInstaller@0
      displayName: 'Install Docker 17.09.0-ce'
      inputs:
        dockerVersion: 17.09.0-ce
        releaseType: stable
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        containerRegistry: $(ACR_CONNECTION_NAME)
        command: login
    - bash: |
        git clone -b $(BRANCH_NAME) https://github.com/apache/spark
        cd spark
        sparkdir=$(pwd)
        ./build/mvn -Pkubernetes -DskipTests clean package
        ./bin/docker-image-tool.sh -r $(ACR_URL) -t $(Build.BuildId) build
    - task: Docker@2
      displayName: Push image to ACR
      inputs:
        containerRegistry: $(ACR_CONNECTION_NAME)
        repository: $(IMAGE_NAME)
        command: 'push'
        tags: '$(Build.BuildId)'